routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\DashController;
use App\Http\Controllers\DraftController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RatingController;
use App\Http\Controllers\SarprasController;
use App\Http\Controllers\SarprasKeluarController;
use App\Http\Controllers\SarprasMasukController;
use App\Http\Controllers\ValidasiController;
use App\Http\Controllers\WhatsAppController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

Route::get('/pengguna/export', [PenggunaController::class, 'userexport'])->name('pengguna.export');
Route::post('/pengguna/import', [PenggunaController::class, 'userimport'])->name('pengguna.import');
Route::resource('pengguna', PenggunaController::class);
Route::post('/pengguna/{id}/edit', [PenggunaController::class, 'password']);

Route::get('/', [DashController::class, 'welcome']);
Route::get('/dashboard', [DashController::class, 'index'])->name('dashboard');
Route::get('/barang', [DashController::class, 'barang']);
Route::get('/ruangan', [DashController::class, 'ruangan']);
Route::get('/sarpras_detail/{id}', [DashController::class, 'sarpras_detail']);
Route::get('/about', [DashController::class, 'about']);
Route::get('/contact', [DashController::class, 'contact']);
Route::get('/faqs', [DashController::class, 'faqs']);

Route::get('/draft_count', [DraftController::class, 'draft_count']);
Route::get('/draft_count/{id}', [DraftController::class, 'draft_count_update']);
Route::get('/draft/mini', [DraftController::class, 'mini_draft']);
Route::post('/draft/mini/destroy/{id}', [DraftController::class, 'mini_draft_destroy']);
Route::get('/draft_', [DraftController::class, 'draft_']);
Route::get('/draft_update/{id}', [DraftController::class, 'draft_update']);
Route::put('/draft_qty/{id}', [DraftController::class, 'update_qty']);
Route::resource('draft', DraftController::class);
Route::post('/draft_update/{id}', [DraftController::class, 'draft_update_delete']);
Route::post('/draft/print', [DraftController::class, 'print']);
Route::post('/cek_qrcode', [DraftController::class, 'cek_qr_code']);

Route::resource('sarpras', SarprasController::class);

Route::resource('sarpras_masuk', SarprasMasukController::class);

Route::resource('sarpras_keluar', SarprasKeluarController::class);

Route::resource('validasi', ValidasiController::class);
Route::put('/validasi_update/{id}', [ValidasiController::class, 'update_lanjut']);
Route::get('/validasi_edit/{id}', [ValidasiController::class, 'add_sarpras'])->name('validasi_edit.add');
Route::post('/validasi_edit', [ValidasiController::class, 'store_add_sarpras'])->name('validasi_edit.store');
Route::put('/validasi_edit/{id}', [ValidasiController::class, 'update_peminjaman'])->name('validasi_edit.update');
Route::delete('/validasi_edit/{id}', [ValidasiController::class, 'destroy_sarpras'])->name('validasi_edit.destroy');

Route::resource('peminjaman', PeminjamanController::class);

Route::resource('pengembalian', PengembalianController::class);

Route::get('belum_validasi', [ValidasiController::class, 'belum_validasi']);
Route::get('sudah_validasi', [ValidasiController::class, 'sudah_validasi']);

Route::resource('rating', RatingController::class);

Route::get('/ketersediaan', [LaporanController::class, 'ketersediaan']);
Route::get('/kerusakan', [LaporanController::class, 'kerusakan']);

Route::get('/profile', [ProfileController::class, 'index']);
Route::get('/edit', [ProfileController::class, 'index']);
Route::get('/changePassword', [ProfileController::class, 'index']);
Route::post('/edit/{id}', [ProfileController::class, 'update'])->name('update_profile');
Route::post('/changePassword', [ProfileController::class, 'password'])->name('changePassword');

// Route::match(['get', 'post'], '/botman', [BotManController::class, 'handle']);

Route::get('/perangkat', [WhatsAppController::class, 'perangkat']);
Route::put('/perangkat', [WhatsAppController::class, 'update_sender']);
Route::put('/perangkats', [WhatsAppController::class, 'restart']);

Route::get('/schedule', [WhatsAppController::class, 'schedule']);


/*
|--------------------------------------------------------------------------
| Note
|--------------------------------------------------------------------------
| - Disni saya menggunakan layanan WhatsApp Gateway dari wablas
|
|
*/

app/Models/Sarpras.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sarpras extends Model
{
    use HasFactory;

    protected $table = 'sarpras';
}

app/Http/Controllers/SarprasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sarpras;
use App\Models\SarprasDetail;
use App\Models\SarprasKeluar;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class SarprasController extends Controller
{
    public function index()
    {
        $sarpras = Sarpras::orderBy('jenis', 'asc')->get();

        return view('back.sarpras.index', compact('sarpras'));
    }
    public function create()
    {
        return view('back.sarpras.create');
    }
    public function store(Request $request)
    {
        $request->validate([
            'jenis' => 'required',
            'nama' => ['required', 'string', 'max:255'],
            'deskripsi' => ['required', 'string'],
            'photo' => 'required|image|file|max:8192'
        ]);
        $sarpras = new Sarpras();
        $sarpras->jenis = $request->jenis;
        if ($request->jenis == 'Ruangan') {
            $sarpras->kategori = implode(', ', $request->kategori_rgn);
        } elseif ($request->jenis == 'Barang') {
            $sarpras->kategori = implode(', ', $request->kategori_brg);
        }
        $sarpras->nama = $request->nama;
        $sarpras->jumlah = 0;
        $sarpras->deskripsi = $request->deskripsi;
        $sarpras->photo =  $request->file('photo')->store('sarpras');
        $sarpras->save();

        return redirect('/sarpras');
    }
    public function show($id)
    {
        $sarpras = Sarpras::where('id', $id)->first();
        // $sarpras_detail = DB::table('sarpras_detail')
        //     // $sarpras_detail = SarprasDetail::whereNull('draft_id')
        //     ->join('sarpras_masuk', 'sarpras_masuk.id', '=', 'sarpras_detail.sarpras_masuk_id')->where('sarpras_masuk.draft_id', '=', NULL)
        //     // ->join('sarpras_keluar', 'sarpras_keluar.id', '=', 'sarpras_detail.sarpras_keluar_id')->where('sarpras_keluar.draft_id', '=', NULL)
        //     ->select([
        //         // DB::raw('sum(sarpras_keluar.jumlah) as jumlah_k'),
        //         DB::raw('sum(sarpras_masuk.jumlah) as jumlah_m'),
        //         DB::raw('MONTH(sarpras_detail.created_at) as bulan'),
        //         DB::raw('YEAR(sarpras_detail.created_at) as tahun')
        //     ])->groupBy(['bulan', 'tahun'])->get()->toArray();
        // dd($sarpras_detail);
        return view('back.sarpras.show', compact('sarpras'));
    }
    public function edit($id)
    {
        $sarpras = Sarpras::where('id', $id)->first();

        return view('back.sarpras.edit', compact('sarpras'));
    }
    public function update(Request $request, $id)
    {
        $request->validate([
            'jenis' => 'required',
            'nama' => ['required', 'string', 'max:255'],
            'deskripsi' => ['required', 'string'],
            'photo' => 'image|file|max:8192'
        ]);
        Sarpras::where('id', $id)
            ->update([
                'jenis' => $request->jenis,
                'nama' => $request->nama,
                'deskripsi' => $request->deskripsi
            ]);
        if ($request->jenis == 'Ruangan') {
            Sarpras::where('id', $id)
                ->update([
                    'kategori' => implode(', ', $request->kategori_rgn)
                ]);
        } elseif ($request->jenis == 'Barang') {
            Sarpras::where('id', $id)
                ->update([
                    'kategori' => implode(', ', $request->kategori_brg)
                ]);
        }
        if ($request->file('photo')) {
            Storage::delete($request->old_photo);
            Sarpras::where('id', $id)
                ->update([
                    'photo' => $request->file('photo')->store('sarpras')
                ]);
        }
        return redirect('/sarpras');
    }
    public function destroy(Request $request, $id)
    {
        Storage::delete($request->old_photo);
        Sarpras::destroy($id);

        return redirect('/sarpras');
    }
}

resources/views/back/sarpras/create.blade.php
@extends('back.layouts.index')
@push('title', 'Create | Sarpras')
@section('content')
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Create Sarpras</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="#!">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Pages</span></li>
                <li><span>Sarpras</span></li>
                <li><span style="margin-right: 20px;">Create</span></li>
            </ol>
        </div>
    </header>
    <!-- Start page -->
    <div class="row">
        <div class="col-xs-6">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Select Replacement</h2>
                </header>
                <div class="panel-body">
                    <form class="form-horizontal form-bordered" action="{{ route('sarpras.store') }}" method="POST" id="formcreate" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group @error('jenis') has-error @enderror">
                            <label class="col-md-3 control-label">Jenis<span class="required">*</span></label>
                            <div class="col-md-8">
                                <select data-plugin-selectTwo class="form-control" name="jenis" id="jenis" onchange="showKategori(this)">
                                    <option selected disabled></option>
                                    <option value="Ruangan">Ruangan</option>
                                    <option value="Barang">Barang</option>
                                </select>
                                @error('jenis')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group" id="barang">
                            <label class="col-md-3 control-label">Kategori</label>
                            <div class="col-md-6">
                                <select class="form-control" multiple="multiple" name="kategori_brg[]" data-plugin-multiselect id="ms_example0">
                                    <option value="elektronik">Elektronik</option>
                                    <option value="mebel">Mebel</option>
                                    <option value="lainnya">Lainnya</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group" id="ruangan">
                            <label class="col-md-3 control-label">Kategori</label>
                            <div class="col-md-6">
                                <select class="form-control" multiple="multiple" name="kategori_rgn[]" data-plugin-multiselect id="ms_example0">
                                    <option value="kelas">Kelas</option>
                                    <option value="lainnya">Lainnya</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group @error('nama') has-error @enderror">
                            <label class="col-md-3 control-label" for="nama">Nama<span class="required">*</span></label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" value="{{old('nama')}}" id="nama" name="nama">
                                @error('nama')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group @error('deskripsi') has-error @enderror">
                            <label class="col-md-3 control-label" for="deskripsi">Deskripsi<span class="required">*</span></label>
                            <div class="col-md-8">
                                <textarea name="deskripsi" id="deskripsi" rows="5" class="form-control" placeholder="Describe sarpras">{{old('deskripsi')}}</textarea>
                                @error('deskripsi')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group @error('photo') has-error @enderror">
                            <label class="col-md-3 control-label" for="Photo">Photo<span class="required">*</span></label>
                            <div class="col-md-8">
                                <input type="file" class="form-control" id="Photo" name="photo" onchange="previewImage(this)">
                                <img src="" id="preview_sarpras" class="rounded img-responsive" style="width: 35vh; margin-top:10px;">
                                @error('photo')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-9 col-md-offset-3">
                            <button onclick="document.getElementById('formcreate').submit()" class="btn btn-primary">Submit</button>
                            <button onclick="document.getElementById('formcreate').reset()" class="btn btn-default">Reset</button>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <!-- End page -->
</section>
</div>
@endsection

@push('style')
<!-- Specific Page Vendor CSS -->
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/select2/select2.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
@endpush

@push('script')
<script src="{{ asset('/back') }}/vendor/jquery-validation/jquery.validate.js"></script>
<!-- Specific Page Vendor -->
<script src="{{ asset('/back') }}/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
<script src="{{ asset('/back') }}/vendor/select2/select2.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-maskedinput/jquery.maskedinput.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
<script src="{{ asset('/back') }}/vendor/fuelux/js/spinner.js"></script>
<script src="{{ asset('/back') }}/vendor/dropzone/dropzone.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-markdown/js/markdown.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-markdown/js/to-markdown.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-markdown/js/bootstrap-markdown.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/lib/codemirror.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/addon/selection/active-line.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/addon/edit/matchbrackets.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/mode/javascript/javascript.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/mode/xml/xml.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/mode/css/css.js"></script>
<script src="{{ asset('/back') }}/vendor/summernote/summernote.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-maxlength/bootstrap-maxlength.js"></script>
<script src="{{ asset('/back') }}/vendor/ios7-switch/ios7-switch.js"></script>
<script>
    function previewImage(input) {
        var file = $("input[type=file]").get(0).files[0];
        if (file) {
            var reader = new FileReader();
            reader.onload = function() {
                $('#preview_sarpras').attr("src", reader.result);
            }
            reader.readAsDataURL(file);
        }
    }

    $("#barang").hide();
    $("#ruangan").hide();

    function showKategori(elem) {
        if (elem.value == 'Ruangan') {
            $("#ruangan").show();
            $("#barang").hide();
        } else if (elem.value == 'Barang') {
            $('#barang').show();
            $("#ruangan").hide();
        }
    }
</script>
@endpush

@push('last_script')
<!-- Examples -->
<script src="{{ asset('/back') }}/javascripts/forms/examples.advanced.form.js"></script>
@endpush

resources/views/back/sarpras/edit.blade.php
@extends('back.layouts.index')
@push('title', 'Edit | Sarpras')
@section('content')
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Edit Sarpras</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="#!">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Pages</span></li>
                <li><span>Sarpras</span></li>
                <li><span style="margin-right: 20px;">Edit</span></li>
            </ol>
        </div>
    </header>
    <!-- Start page -->
    <div class="row">
        <div class="col-xs-6">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Select Replacement</h2>
                </header>
                <div class="panel-body">
                    <form class="form-horizontal form-bordered" action="{{ route('sarpras.update', $sarpras->id) }}" method="POST" id="formEdit" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="form-group @error('jenis') has-error @enderror">
                            <label class="col-md-3 control-label">Jenis<span class="required">*</span></label>
                            <div class="col-md-8">
                                <select data-plugin-selectTwo class="form-control" id="jenis" name="jenis" onchange="showKategori(this)">
                                    <option value="Ruangan" {{ $sarpras->jenis == 'Ruangan' ? 'selected' : null }}>Ruangan</option>
                                    <option value="Barang" {{ $sarpras->jenis == 'Barang' ? 'selected' : null }}>Barang</option>
                                </select>
                                @error('jenis')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <?php
                        $pecah_string = explode(", ", $sarpras->kategori);
                        ?>
                        <div class="form-group" id="barang">
                            <label class="col-md-3 control-label">Kategori</label>
                            <div class="col-md-6">
                                <select class="form-control" multiple="multiple" name="kategori_brg[]" data-plugin-multiselect id="ms_example0">
                                    <option value="elektronik" @foreach($pecah_string as $data) {{ $data == 'elektronik' ? 'selected' : null }} @endforeach>Elektronik</option>
                                    <option value="mebel" @foreach($pecah_string as $data) {{ $data == 'mebel' ? 'selected' : null }} @endforeach>Mebel</option>
                                    <option value="lainnya" @foreach($pecah_string as $data) {{ $data == 'lainnya' ? 'selected' : null }} @endforeach>Lainnya</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group" id="ruangan">
                            <label class="col-md-3 control-label">Kategori</label>
                            <div class="col-md-6">
                                <select class="form-control" multiple="multiple" name="kategori_rgn[]" data-plugin-multiselect id="ms_example0">
                                    <option value="kelas" @foreach($pecah_string as $data) {{ $data == 'kelas' ? 'selected' : null }} @endforeach>Kelas</option>
                                    <option value="lainnya" @foreach($pecah_string as $data) {{ $data == 'lainnya' ? 'selected' : null }} @endforeach>Lainnya</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group @error('nama') has-error @enderror">
                            <label class="col-md-3 control-label" for="nama">Nama<span class="required">*</span></label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" id="nama" value="{{$sarpras->nama}}" name="nama">
                                @error('nama')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group @error('deskripsi') has-error @enderror">
                            <label class="col-md-3 control-label" for="deskripsi">Deskripsi<span class="required">*</span></label>
                            <div class="col-md-8">
                                <textarea name="deskripsi" id="deskripsi" rows="5" class="form-control">{{$sarpras->deskripsi}}</textarea>
                                @error('deskripsi')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group @error('photo') has-error @enderror">
                            <label class="col-md-3 control-label" for="Photo">Photo<span class="required">*</span></label>
                            <div class="col-md-8">
                                <input type="hidden" name="old_photo" value="{{$sarpras->photo}}">
                                <input type="file" class="form-control" id="Photo" name="photo" onchange="previewImage(this)">
                                <img src="{{  url('/storage/'. $sarpras->photo) }}" id="preview_sarpras" class="rounded img-responsive" style="width: 35vh; margin-top:10px;">
                                @error('photo')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-9 col-md-offset-3">
                            <button onclick="document.getElementById('formEdit').submit()" class="btn btn-primary">Submit</button>
                            <button onclick="document.getElementById('formEdit').reset()" class="btn btn-default">Reset</button>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <!-- End page -->
</section>
</div>
@endsection

@push('style')
<!-- Specific Page Vendor CSS -->
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/select2/select2.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
@endpush

@push('script')
<script src="{{ asset('/back') }}/vendor/jquery-validation/jquery.validate.js"></script>
<!-- Specific Page Vendor -->
<script src="{{ asset('/back') }}/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
<script src="{{ asset('/back') }}/vendor/select2/select2.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
<script>
    function previewImage(input) {
        var file = $("input[type=file]").get(0).files[0];
        if (file) {
            var reader = new FileReader();
            reader.onload = function() {
                $('#preview_sarpras').attr("src", reader.result);
            }
            reader.readAsDataURL(file);
        }
    }
    if ($('#jenis').val() == 'Ruangan') {
        $("#barang").hide();
    } else if ($('#jenis').val() == 'Barang') {
        $("#ruangan").hide();
    }

    function showKategori(elem) {
        if (elem.value == 'Ruangan') {
            $("#ruangan").show();
            $("#barang").hide();
        } else if (elem.value == 'Barang') {
            $('#barang').show();
            $("#ruangan").hide();
        }
    }
</script>
@endpush

@push('last_script')
<!-- Examples -->
<script src="{{ asset('/back') }}/javascripts/forms/examples.advanced.form.js"></script>
@endpush

resources/views/back/sarpras/show.blade.php
@extends('back.layouts.index')
@push('title', 'Show | Sarpras')
@section('content')
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Show Sarpras</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="#!">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Pages</span></li>
                <li><span>Sarpras</span></li>
                <li><span style="margin-right: 20px;">Show</span></li>
            </ol>
        </div>
    </header>
    <!-- Start page -->
    <div class="row">
        <div class="col-md-8">
            <section class="panel panel-featured panel-featured-dark">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Title</h2>
                </header>
                <div class="panel-body">
                    <div class="row" style="margin-bottom: 4vw;">
                        <div class="col-md-12 col-sm-12 col-lg-5">
                            <img src="{{ url('/storage/'. $sarpras->photo) }}" id="previewkk" style=" width: 19vw;min-width: 100px; margin-top: 5px;">
                        </div>
                        <div class="col-md-12 col-sm-12 col-lg-7">
                            <h4 class="display-4">{{$sarpras->nama}}</h4>
                            <div class="form-group">
                                <h5 class="col-md-3">Jumlah</h5>
                                <h5 class="col-md-9">{{$sarpras->jumlah}}</h5>
                            </div>
                            <div class="form-group">
                                <h5 class="col-md-3">Kategori</h5>
                                <h5 class="col-md-9">{{$sarpras->kategori}}</h5>
                            </div>
                            <div class="form-group">
                                <h5 class="col-md-3">Deskripsi</h5>
                                <h5 class="col-md-9">{{$sarpras->deskripsi}}</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <!-- End page -->
</section>
</div>
@endsection