routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\DashController;
use App\Http\Controllers\DraftController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RatingController;
use App\Http\Controllers\SarprasController;
use App\Http\Controllers\SarprasKeluarController;
use App\Http\Controllers\SarprasMasukController;
use App\Http\Controllers\ValidasiController;
use App\Http\Controllers\WhatsAppController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

Route::get('/pengguna/export', [PenggunaController::class, 'userexport'])->name('pengguna.export');
Route::post('/pengguna/import', [PenggunaController::class, 'userimport'])->name('pengguna.import');
Route::resource('pengguna', PenggunaController::class);
Route::post('/pengguna/{id}/edit', [PenggunaController::class, 'password']);

Route::get('/', [DashController::class, 'welcome']);
Route::get('/dashboard', [DashController::class, 'index'])->name('dashboard');
Route::get('/barang', [DashController::class, 'barang']);
Route::get('/ruangan', [DashController::class, 'ruangan']);
Route::get('/sarpras_detail/{id}', [DashController::class, 'sarpras_detail']);
Route::get('/about', [DashController::class, 'about']);
Route::get('/contact', [DashController::class, 'contact']);
Route::get('/faqs', [DashController::class, 'faqs']);

Route::get('/draft_count', [DraftController::class, 'draft_count']);
Route::get('/draft_count/{id}', [DraftController::class, 'draft_count_update']);
Route::get('/draft/mini', [DraftController::class, 'mini_draft']);
Route::post('/draft/mini/destroy/{id}', [DraftController::class, 'mini_draft_destroy']);
Route::get('/draft_', [DraftController::class, 'draft_']);
Route::get('/draft_update/{id}', [DraftController::class, 'draft_update']);
Route::put('/draft_qty/{id}', [DraftController::class, 'update_qty']);
Route::resource('draft', DraftController::class);
Route::post('/draft_update/{id}', [DraftController::class, 'draft_update_delete']);
Route::post('/draft/print', [DraftController::class, 'print']);
Route::post('/cek_qrcode', [DraftController::class, 'cek_qr_code']);

Route::resource('sarpras', SarprasController::class);

Route::resource('sarpras_masuk', SarprasMasukController::class);

Route::resource('sarpras_keluar', SarprasKeluarController::class);

Route::resource('validasi', ValidasiController::class);
Route::put('/validasi_update/{id}', [ValidasiController::class, 'update_lanjut']);
Route::get('/validasi_edit/{id}', [ValidasiController::class, 'add_sarpras'])->name('validasi_edit.add');
Route::post('/validasi_edit', [ValidasiController::class, 'store_add_sarpras'])->name('validasi_edit.store');
Route::put('/validasi_edit/{id}', [ValidasiController::class, 'update_peminjaman'])->name('validasi_edit.update');
Route::delete('/validasi_edit/{id}', [ValidasiController::class, 'destroy_sarpras'])->name('validasi_edit.destroy');

Route::resource('peminjaman', PeminjamanController::class);

Route::resource('pengembalian', PengembalianController::class);

Route::get('belum_validasi', [ValidasiController::class, 'belum_validasi']);
Route::get('sudah_validasi', [ValidasiController::class, 'sudah_validasi']);

Route::resource('rating', RatingController::class);

Route::get('/ketersediaan', [LaporanController::class, 'ketersediaan']);
Route::get('/kerusakan', [LaporanController::class, 'kerusakan']);

Route::get('/profile', [ProfileController::class, 'index']);
Route::get('/edit', [ProfileController::class, 'index']);
Route::get('/changePassword', [ProfileController::class, 'index']);
Route::post('/edit/{id}', [ProfileController::class, 'update'])->name('update_profile');
Route::post('/changePassword', [ProfileController::class, 'password'])->name('changePassword');

// Route::match(['get', 'post'], '/botman', [BotManController::class, 'handle']);

Route::get('/perangkat', [WhatsAppController::class, 'perangkat']);
Route::put('/perangkat', [WhatsAppController::class, 'update_sender']);
Route::put('/perangkats', [WhatsAppController::class, 'restart']);

Route::get('/schedule', [WhatsAppController::class, 'schedule']);


/*
|--------------------------------------------------------------------------
| Note
|--------------------------------------------------------------------------
| - Disni saya menggunakan layanan WhatsApp Gateway dari wablas
|
|
*/

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Validasi;
use App\Models\Pengembalian;
use App\Models\Rating;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class ProfileController extends Controller
{
    public function index()
    {
        if (Auth::user()) {
            if (Auth::user()->roles == 'Mahasiswa' || Auth::user()->roles == 'Dosen') {
                $permohonan = Validasi::where('user_id', Auth::user()->id)->where('status', 0)->get();
                $peminjaman = Pengembalian::where('user_id', Auth::user()->id)->whereNotIn('status', [1])->get();
                $pengembalian = Pengembalian::where('user_id', Auth::user()->id)->where('status', 1)->get();

                $rating = Rating::where('user_id', Auth::user()->id)->first();
                if ($rating) {

                    $jumlah = count(Rating::where('user_id', Auth::user()->id)->get());
                    $star = Rating::where('user_id', Auth::user()->id)->pluck('penilaian')->sum();

                    $rate = $star / $jumlah;
                    if (strlen($rate) == 1) {
                        $rate = number_format($rate, 1);
                    }
                } else {
                    $jumlah = 0;
                    $rate = 0;
                }

                return view('front.profile.index', compact('permohonan', 'peminjaman', 'pengembalian', 'rate', 'jumlah'));
            } else {
                return view('back.profile.index');
            }
        } else {
            return abort(403);
        }
    }
    public function update(Request $request, $id)
    {
        if (Auth::user()->roles == 'Mahasiswa' || Auth::user()->roles == 'Dosen') {
            $nama = $request->name;
            $email = $request->email;
            $no_telp = $request->no_telp;

            $cek_email = User::where('email', $email)->whereNotIn('id', [$id])->first();
            $cek_telp = User::where('no_telp', $no_telp)->whereNotIn('id', [$id])->first();
            // dd($cek_telp);
            if (is_null($nama) && is_null($email) && is_null($no_telp)) {
                return response()->json(
                    [
                        'error_nama' => 'nama tidak boleh kosong',
                        'error_email' => 'email tidak boleh kosong',
                        'error_no_telp' => 'nomer tidak boleh kosong'
                    ]
                );
            } elseif (is_null($nama) && is_null($email)) {
                return response()->json(
                    [
                        'error_nama' => 'nama tidak boleh kosong',
                        'error_email' => 'email tidak boleh kosong',
                    ]
                );
            } elseif (is_null($email) && is_null($no_telp)) {
                return response()->json(
                    [
                        'error_email' => 'email tidak boleh kosong',
                        'error_no_telp' => 'nomer tidak boleh kosong'
                    ]
                );
            } elseif (is_null($no_telp) && is_null($nama)) {
                return response()->json(
                    [
                        'error_nama' => 'nama tidak boleh kosong',
                        'error_no_telp' => 'nomer tidak boleh kosong'
                    ]
                );
            } elseif (is_null($nama)) {
                return response()->json(['error_nama' => 'nama tidak boleh kosong']);
            } elseif (is_null($email)) {
                return response()->json(['error_email' => 'email tidak boleh kosong']);
            } elseif (is_null($no_telp)) {
                return response()->json(['error_no_telp' => 'nomer tidak boleh kosong']);
            } elseif ($cek_telp != null && $cek_email != null) {
                return response()->json(
                    [
                        'error_email' => 'email sudah terdaftar',
                        'error_no_telp' => 'nomor sudah terdaftar'
                    ]
                );
            } elseif ($cek_email) {
                return response()->json([
                    'error_email' => 'email sudah terdaftar'
                ]);
            } elseif ($cek_telp) {
                return response()->json([
                    'error_no_telp' => 'nomor sudah terdaftar'
                ]);
            }

            User::where('id', $id)
                ->update([
                    'name' => $request->name,
                    'email' => $request->email,
                    'jenis_kelamin' => $request->jenis_kelamin,
                    'alamat' => $request->alamat,
                    'rt' => $request->rt,
                    'rw' => $request->rw,
                    'kota' => $request->kota,
                    'no_telp' => $request->no_telp
                ]);

            if ($request->file('photo')) {
                if ($request->old_photo) {
                    Storage::delete($request->old_photo);
                }
                User::where('id', $id)
                    ->update([
                        'photo_profile' => $request->file('photo')->store('photo')
                    ]);
            }

            return response()->json(['success_message' => 'berhasil update biodata']);
        } else {
            $request->validate([
                'nama' => 'required',
                'email' => 'required',
                'nim_nidn' => 'required',
                'photo_profile' => 'image|file|max:8192'
            ]);
            User::where('id', $id)
                ->update([
                    'name' => $request->nama,
                    'email' => $request->email,
                    'nim_nidn' => $request->nim_nidn,
                    'jenis_kelamin' => $request->jenis_kelamin,
                    'alamat' => $request->alamat,
                    'rt' => $request->rt,
                    'rw' => $request->rw,
                    'desa' => $request->desa,
                    'kota' => $request->kota,
                    'no_telp' => $request->no_telp
                ]);
            if ($request->file('photo_profile')) {
                Storage::delete($request->old_photo);
                User::where('id', $id)
                    ->update([
                        'photo_profile' => $request->file('photo_profile')->store('photo')
                    ]);
            }
            return redirect('/edit');
        }
    }
    public function password(Request $request)
    {
        if (Auth::user()->roles == 'Mahasiswa' || Auth::user()->roles == 'Dosen') {

            $request->validate([
                'old_password' => 'required',
                'password' => ['required', 'string', 'min:8', 'confirmed']
            ]);

            if (Hash::check($request->old_password, Auth::user()->password)) {
                Auth::user()->update([
                    'password' => bcrypt($request->password)
                ]);
                User::where('id', Auth::user()->id)
                    ->update([
                        'password_tidack_enkripsi' => $request->password
                    ]);
                return response()->json([
                    'success_message' => 'Berhasil ubah password'
                ]);
            } else {
                return response()->json([
                    'error_message' => 'Password yang dimasukkan salah'
                ]);
            }
        } else {
            $request->validate([
                'old_password' => 'required',
                'password' => ['required', 'string', 'min:8', 'confirmed']
            ]);

            if (Hash::check($request->old_password, Auth::user()->password)) {
                Auth::user()->update([
                    'password' => bcrypt($request->password)
                ]);
                User::where('id', Auth::user()->id)
                    ->update([
                        'password_tidack_enkripsi' => $request->password
                    ]);
                return redirect('/profile');
            } else {
                return view('back.profile.index')->withErrors(['old_password' => 'Password yang anda masukkan salah']);
            }
        }
    }
}

resources/views/front/profile/edit.blade.php
@extends('front.layouts.index_')
@push('title', 'Draft')
@section('content')
<!-- breadcrumb -->
<div class="container">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
        <a href="/" class="stext-109 cl8 hov-cl1 trans-04">
            Home
            <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
        </a>
        <span class="stext-109 cl4">
            Draft
            <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
        </span>
        <span class="stext-109 cl4">
            Edit
        </span>
    </div>
</div>
<!-- Shoping Cart -->
<div class="bg0 p-t-55 p-b-85">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
                <div class="m-l-25 m-r--38 m-lr-0-xl">
                    <div class="wrap-table-shopping-cart">
                        <table class="table-shopping-cart" id="table_draft_update">

                        </table>
                    </div>
                </div>
            </div>
            <form action="{{ route('validasi.update', $validasi->id) }}" method="POST" enctype="multipart/form-data" class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-10">
                @csrf
                @method('put')
                <!-- bor10 card p-b-10 m-l-63 m-r-40 m-lr-0-xl -->
                <div class="bor10 card p-lr-25 p-t-30 p-b-10 m-l-63 m-r-25 m-lr-0-xl p-lr-15-sm">
                    <h4 class="mtext-109 cl2 p-b-30">
                        Data Permohonan
                    </h4>

                    <div class="flex-w flex-t bor12 p-b-13">
                        <div class="size-208">
                            <span class="stext-110 cl2">
                                Total
                            </span>
                        </div>

                        <div class="size-209">
                            <span class="mtext-110 cl2" id="total_draft_update"></span>
                        </div>
                    </div>
                    <div class="flex-w flex-t  p-t-15 p-b-10">
                        <div class="size-208 w-full-ssm">
                            <span class="stext-110 cl2">
                                Keperluan
                            </span>
                        </div>
                        <div class="bor8 bg0 m-b-12 w-full">
                            <input type="hidden" value="{{Auth::user()->id}}" name="user_id">
                            <textarea class="form-control @error('keperluan') is-invalid @enderror stext-113 cl2 size-110" id="textArea" type="text" name="keperluan" autocomplete="off">
                            {{ $validasi->keperluan }}
                            </textarea>
                        </div>
                        @error('keperluan')
                        <strong class="text-danger">{{ $message }}</strong>
                        @enderror
                    </div>
                    <div class="flex-w flex-t  p-t-15 p-b-10">
                        <div class="size-209 w-full-ssm">
                            <span class="stext-110 cl2">
                                Proposal Baru
                            </span>
                        </div>
                        <div class="bor8 bg0 m-b-12 w-full">
                            <input type="hidden" name="old_proposal" value="{{$validasi->proposal}}">
                            <input class="form-control @error('proposal') is-invalid @enderror" type="file" name="proposal">
                        </div>
                        @error('proposal')
                        <strong class="text-danger">{{ $message }}</strong>
                        @enderror
                    </div>
                    <div class="flex-w flex-t  p-t-15 p-b-10">
                        <div class="size-209 w-full-ssm">
                            <span class="stext-110 cl2">
                                Proposal Lama
                            </span>
                        </div>
                        <div class="bor8 bg0 m-b-12 w-full">
                            <a href="/storage/{{ $validasi->proposal }}" class="btn btn-success w-full" target="_blank" rel="noopener noreferrer">
                                Download
                            </a>
                        </div>
                    </div>
                    <div class="flex-w flex-t  p-t-15 p-b-30">
                        <div class="size-208 w-full-ssm">
                            <span class="stext-110 cl2">
                                Tanggal
                            </span>
                        </div>
                        <div class="row" id="pickers">
                            <div class="col-md-6">
                                <input type="text" class="form-control @error('tanggal') is-invalid @enderror" name="tanggal" id="start" value="{{ date('Y-m-d H:i', strtotime($validasi->tanggal_start)) }}" autocomplete="off">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control @error('sampai') is-invalid @enderror" name="sampai" id="end" value="{{ date('Y-m-d H:i', strtotime($validasi->tanggal_finish)) }}" autocomplete="off">
                            </div>
                        </div>
                        @error('tanggal')
                        <strong class="text-danger">{{ $message }}</strong>
                        @enderror
                        @error('sampai')
                        <strong class="text-danger">{{ $message }}</strong>
                        @enderror
                    </div>
                    <div class="flex-w">
                        <button type="submit" class="flex-c-m stext-101 cl0 size-115 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">
                            Simpan
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('style')
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
@endpush

@push('script')
<script src="{{ asset('/front') }}/vendor/sweetalert/sweetalert.min.js"></script>
<!--===============================================================================================-->
<script src="{{ asset('/front') }}/vendor/daterangepicker/moment.min.js"></script>
<script src="{{ asset('/front') }}/vendor/daterangepicker/daterangepicker.js"></script>
<script>
    // ambil url 
    var URLpath = window.location.pathname;

    // pisah url
    var pathArray = URLpath.split('/');

    // ambil id validasi
    var idValidasi = pathArray[2];

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $.ajax({
        method: "GET",
        url: "/draft_update/" + idValidasi,
        success: function(data) {
            $("#table_draft_update").html(data);
            totalDraf_Update();
        }
    })

    function Update_Draft() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $.ajax({
            method: "GET",
            url: "/draft_update/" + idValidasi,
            success: function(data) {
                $("#table_draft_update").html(data);
                totalDraf_Update();
            }
        })
    }

    function totalDraf_Update() {
        $.ajax({
            type: 'GET',
            url: '/draft_count/' + idValidasi,
            success: function(response) {
                var response = JSON.parse(response);
                $('#total_draft_update').text(response);
            }
        })
    }

    function draft_destroy_update(id) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $.ajax({
            method: "post",
            url: "/draft_update/" + id,
            success: function(response) {
                if (response.tes == 'Error') {
                    swal("Gagal", response.status, "error");
                }
                Update_Draft();
                totalDraf_Update();
            }
        })
    }

    $('textarea#textArea').html($('textarea#textArea').html().trim());

    $('#pickers').daterangepicker({
        opens: 'left',
        timePicker: true,
        startDate: moment().startOf('hour'),
        endDate: moment().startOf('hour').add(32, 'hour'),
        locale: {
            format: 'YYYY-MM-DD hh:mm'
        }
    }, function(start, end, label) {
        $('#start').val(start.format('YYYY-MM-DD hh:mm'))
        $('#end').val(end.format('YYYY-MM-DD hh:mm'))
    });
</script>
@endpush

resources/views/front/profile/modal.blade.php
<div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-10">
        <div class="bg0 how-pos3-parent">
            <button class="how-pos3 hov3 trans-04 js-hide-modal1">
                <img src="{{ asset('/front') }}/images/icons/icon-close.png" alt="CLOSE">
            </button>

            <div class="row">
                <form action="{{ route('update_profile', Auth::user()->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="col-md-3 col-lg-5 col-sm-4">
                        <div class="wrap-slick3-dots"></div>
                        <div class="wrap-slick3-arrows flex-sb-m flex-w"></div>

                        <div class="gallery-lb">
                            <div class="wrap-pic-w pos-relative">
                                @if(Auth::user()->photo_profile)
                                <img src="{{ url('/storage/'. Auth::user()->photo_profile) }}" id="preview_photo" alt="IMG-PRODUCT">
                                <a class="flex-c-m size-108 m-l-20 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04 zoom-picture" href="{{ url('/storage/'. Auth::user()->photo_profile)}}">
                                    <i class="fa fa-expand"></i>
                                </a>
                                @else
                                <img src="https://ui-avatars.com/api/?name={{ Auth::user()->name }}" id="preview_photo" alt="IMG-PRODUCT">
                                @endif
                                <input type="hidden" id="old_photo_profile" value="{{ Auth::user()->photo_profile }}">
                                <input class="stext-111 cl2 plh3 p-l-62 p-r-30" id="photo" type="file" name="photo" style="opacity: 0; height:1px; display:none;" onchange="previewImage(this)">
                                <button onclick="window.location.href='javascript:void(0)'" class="changePhoto" id="change_picture">Ganti Foto</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-9 col-lg-7 col-sm-8 p-b-30">
                        <div class="p-r-50 p-t-30 p-lr-0-lg">
                            <label for="">Nama</label>
                            <input type="hidden" name="" id="id_edit" value="{{ Auth::user()->id }}">
                            <div class="bor8 m-b-20 how-pos4-parent">
                                <input class="stext-111 cl2 plh3 size-126 p-l-62 p-r-30" id="nama_edit" type="text" name="name" placeholder="Your Username" value="{{ Auth::user()->name }}">
                                <i class="how-pos4 pointer-none fa fa-user-o"></i>
                            </div>
                            <p class="text-danger m-b-20" style="margin-top: -20px;" id="nama_e"></p>
                            <label for="">Email</label>
                            <div class="bor8 m-b-20 how-pos4-parent w-100">
                                <input class="stext-111 cl2 plh3 size-126 p-l-62 p-r-30" id="email_edit" type="email" name="email" placeholder="Your Email Address" value="{{ Auth::user()->email }}">
                                <i class="how-pos4 pointer-none fa fa-envelope-o"></i>
                            </div>
                            <p class="text-danger m-b-20" style="margin-top: -20px;" id="email_e"></p>
                            <div class="row">
                                <div class="col-6">
                                    <label for="">WhatsApp</label>
                                    <div class="bor8 m-b-20 how-pos4-parent w-100">
                                        <input class="stext-111 cl2 plh3 size-126 p-l-62 p-r-30" id="no_telp_edit" type="number" name="no_telp" placeholder="Your Number Phone" value="{{ Auth::user()->no_telp }}">
                                        <i class="how-pos4 pointer-none fa fa-whatsapp"></i>
                                    </div>
                                    <p class="text-danger m-b-20" style="margin-top: -20px;" id="no_telp_e"></p>
                                </div>
                                <div class="col-6">
                                    Jenis Kelamin
                                    <div class="bor8 m-b-20 how-pos4-parent w-100">
                                        <select class="stext-111 cl2 plh3 size-126 p-l-62 p-r-30 bor8" id="jenis_kelamin" name="jenis_kelamin">
                                            <option value="" selected disabled>Pilih</option>
                                            <option data-value="Laki-laki" {{ Auth::user()->jenis_kelamin == 'Laki-laki' ? 'selected' : null }}>Laki-laki</option>
                                            <option data-value="Perempuan" {{ Auth::user()->jenis_kelamin == 'Perempuan' ? 'selected' : null }}>Perempuan</option>
                                            <option data-value="Not Found" {{ Auth::user()->jenis_kelamin == 'Not Found' ? 'selected' : null }}>Not Found</option>
                                        </select>
                                        <i class="how-pos4 pointer-none fa fa-transgender"></i>
                                    </div>
                                </div>
                            </div>
                            <label for="">Alamat</label>
                            <div class="bor8 m-b-20 how-pos4-parent w-100">
                                <input class="stext-111 cl2 plh3 size-126 p-l-62 p-r-30" id="alamat_edit" type="text" name="alamat" placeholder="Your Location Address" value="{{ Auth::user()->alamat }}">
                                <i class="how-pos4 pointer-none fa fa-map-marker"></i>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <label for="">Rt</label>
                                    <div class="bor8 m-b-20 how-pos4-parent w-100">
                                        <input class="stext-111 cl2 plh3 size-126 p-l-62 p-r-30" id="rt_edit" type="number" name="rt" placeholder="Your Location Address" value="{{ Auth::user()->rt }}">
                                        <i class="how-pos4 pointer-none fa fa-map-marker"></i>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <label for="">Rw</label>
                                    <div class="bor8 m-b-20 how-pos4-parent w-100">
                                        <input class="stext-111 cl2 plh3 size-126 p-l-62 p-r-30" id="rw_edit" type="number" name="rw" placeholder="Your Location Address" value="{{ Auth::user()->rw }}">
                                        <i class="how-pos4 pointer-none fa fa-map-marker"></i>
                                    </div>
                                </div>
                            </div>
                            <label for="">Kota</label>
                            <div class="bor8 m-b-20 how-pos4-parent w-100">
                                <input class="stext-111 cl2 plh3 size-126 p-l-62 p-r-30" id="kota_edit" type="text" name="kota" placeholder="Your Location Address" value="{{ Auth::user()->kota }}">
                                <i class="how-pos4 pointer-none fa fa-map-marker"></i>
                            </div>
                            <button class="savedit">Simpan</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>