routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\DashController;
use App\Http\Controllers\DraftController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RatingController;
use App\Http\Controllers\SarprasController;
use App\Http\Controllers\SarprasKeluarController;
use App\Http\Controllers\SarprasMasukController;
use App\Http\Controllers\ValidasiController;
use App\Http\Controllers\WhatsAppController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

Route::get('/pengguna/export', [PenggunaController::class, 'userexport'])->name('pengguna.export');
Route::post('/pengguna/import', [PenggunaController::class, 'userimport'])->name('pengguna.import');
Route::resource('pengguna', PenggunaController::class);
Route::post('/pengguna/{id}/edit', [PenggunaController::class, 'password']);

Route::get('/', [DashController::class, 'welcome']);
Route::get('/dashboard', [DashController::class, 'index'])->name('dashboard');
Route::get('/barang', [DashController::class, 'barang']);
Route::get('/ruangan', [DashController::class, 'ruangan']);
Route::get('/sarpras_detail/{id}', [DashController::class, 'sarpras_detail']);
Route::get('/about', [DashController::class, 'about']);
Route::get('/contact', [DashController::class, 'contact']);
Route::get('/faqs', [DashController::class, 'faqs']);

Route::get('/draft_count', [DraftController::class, 'draft_count']);
Route::get('/draft_count/{id}', [DraftController::class, 'draft_count_update']);
Route::get('/draft/mini', [DraftController::class, 'mini_draft']);
Route::post('/draft/mini/destroy/{id}', [DraftController::class, 'mini_draft_destroy']);
Route::get('/draft_', [DraftController::class, 'draft_']);
Route::get('/draft_update/{id}', [DraftController::class, 'draft_update']);
Route::put('/draft_qty/{id}', [DraftController::class, 'update_qty']);
Route::resource('draft', DraftController::class);
Route::post('/draft_update/{id}', [DraftController::class, 'draft_update_delete']);
Route::post('/draft/print', [DraftController::class, 'print']);
Route::post('/cek_qrcode', [DraftController::class, 'cek_qr_code']);

Route::resource('sarpras', SarprasController::class);

Route::resource('sarpras_masuk', SarprasMasukController::class);

Route::resource('sarpras_keluar', SarprasKeluarController::class);

Route::resource('validasi', ValidasiController::class);
Route::put('/validasi_update/{id}', [ValidasiController::class, 'update_lanjut']);
Route::get('/validasi_edit/{id}', [ValidasiController::class, 'add_sarpras'])->name('validasi_edit.add');
Route::post('/validasi_edit', [ValidasiController::class, 'store_add_sarpras'])->name('validasi_edit.store');
Route::put('/validasi_edit/{id}', [ValidasiController::class, 'update_peminjaman'])->name('validasi_edit.update');
Route::delete('/validasi_edit/{id}', [ValidasiController::class, 'destroy_sarpras'])->name('validasi_edit.destroy');

Route::resource('peminjaman', PeminjamanController::class);

Route::resource('pengembalian', PengembalianController::class);

Route::get('belum_validasi', [ValidasiController::class, 'belum_validasi']);
Route::get('sudah_validasi', [ValidasiController::class, 'sudah_validasi']);

Route::resource('rating', RatingController::class);

Route::get('/ketersediaan', [LaporanController::class, 'ketersediaan']);
Route::get('/kerusakan', [LaporanController::class, 'kerusakan']);

Route::get('/profile', [ProfileController::class, 'index']);
Route::get('/edit', [ProfileController::class, 'index']);
Route::get('/changePassword', [ProfileController::class, 'index']);
Route::post('/edit/{id}', [ProfileController::class, 'update'])->name('update_profile');
Route::post('/changePassword', [ProfileController::class, 'password'])->name('changePassword');

// Route::match(['get', 'post'], '/botman', [BotManController::class, 'handle']);

Route::get('/perangkat', [WhatsAppController::class, 'perangkat']);
Route::put('/perangkat', [WhatsAppController::class, 'update_sender']);
Route::put('/perangkats', [WhatsAppController::class, 'restart']);

Route::get('/schedule', [WhatsAppController::class, 'schedule']);


/*
|--------------------------------------------------------------------------
| Note
|--------------------------------------------------------------------------
| - Disni saya menggunakan layanan WhatsApp Gateway dari wablas
|
|
*/

app/Models/SarprasKeluar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SarprasKeluar extends Model
{
    use HasFactory;

    protected $table = 'sarpras_keluar';

    public function sarpras()
    {
        return $this->belongsTo(Sarpras::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/SarprasKeluarController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sarpras;
use App\Models\SarprasDetail;
use App\Models\SarprasKeluar;
use App\Models\SarprasMasuk;
use App\Models\User;
use Illuminate\Http\Request;

class SarprasKeluarController extends Controller
{
    public function index()
    {
        // $user = User::where('roles', 'Mahasiswa')->orWhere('roles', 'Dosen')->get();
        // dd($user);
        $sarpras_keluar = SarprasKeluar::whereNotIn('user_id', User::where('roles', 'Mahasiswa')->orWhere('roles', 'Dosen')->get('id'))
            ->whereNotIn('sarpras_id', [0])->get();

        return view('back.sarpras_keluar.index', compact('sarpras_keluar'));
    }
    public function create()
    {
        $sarpras_brg = Sarpras::where('jenis', 'Barang')->get();
        $sarpras_rgn = Sarpras::where('jenis', 'Ruangan')->get();

        return view('back.sarpras_keluar.create', compact('sarpras_brg', 'sarpras_rgn'));
    }
    public function show($id)
    {
        $sarpras_keluar = SarprasKeluar::where('id', $id)->first();

        return view('back.sarpras_keluar.show', compact('sarpras_keluar'));
    }
    public function store(Request $request)
    {
        $request->validate([
            'sarpras' => 'required',
            'user_id' => 'required',
            'tanggal' => 'required',
            'jumlah' => 'required|numeric',
            'keterangan' => 'required'
        ]);
        $sarpras_keluar = new SarprasKeluar();
        $sarpras_keluar->user_id = $request->user_id;
        $sarpras_keluar->sarpras_id = $request->sarpras;
        $sarpras_keluar->tanggal_keluar = $request->tanggal;
        $sarpras_keluar->jumlah = $request->jumlah;
        $sarpras_keluar->keterangan = $request->keterangan;
        $sarpras_keluar->save();

        $sarpras = Sarpras::where('id', $request->sarpras)->first();
        Sarpras::where('id', $request->sarpras)
            ->update([
                'jumlah' => $sarpras->jumlah - $request->jumlah
            ]);

        $sarpras_keluar_id = SarprasKeluar::all()->max();

        $sarpras_detail = new SarprasDetail();
        $sarpras_detail->sarpras_id = $request->sarpras;
        $sarpras_detail->sarpras_masuk_id = 10;
        $sarpras_detail->sarpras_keluar_id = $sarpras_keluar_id->id;
        $sarpras_detail->save();

        $cek = SarprasMasuk::where('id', 10)->where('keterangan', 'untuk grafik')->first();
        if (is_null($cek)) {
            $sarpras_masuk = new SarprasMasuk();
            $sarpras_masuk->id = 10;
            $sarpras_masuk->user_id = 0;
            $sarpras_masuk->draft_id = 0;
            $sarpras_masuk->sarpras_id = 0;
            $sarpras_masuk->tanggal_masuk = date('y-m-d');
            $sarpras_masuk->jumlah = 0;
            $sarpras_masuk->keterangan = 'untuk grafik';
            $sarpras_masuk->save();
        }

        return redirect('/sarpras_keluar');
    }
    public function update(Request $request, $id)
    {
        $sarpras_id = $request->input('sarpras_id');
        $tanggal = $request->input('tanggal');
        $jumlah_b = $request->input('jumlah');
        $old_jumlah = $request->input('old_jumlah');
        $keterangan = $request->input('keterangan');

        $sarpras = Sarpras::where('id', $sarpras_id)->first();
        $jumlah_a = $sarpras->jumlah - $old_jumlah;
        $jumlah_c = $jumlah_a + $jumlah_b;

        Sarpras::where('id', $sarpras_id)
            ->update([
                'jumlah' => $jumlah_c
            ]);

        SarprasKeluar::where('id', $id)
            ->update([
                'tanggal_keluar' => $tanggal,
                'jumlah' => $jumlah_b
            ]);

        $sarpras_keluar = SarprasKeluar::whereNotIn('user_id', User::where('roles', 'Mahasiswa')->orWhere('roles', 'Dosen')->get('id'))->get();

        return view('back.sarpras_keluar.table', compact('sarpras_keluar'));
    }
    public function destroy($id)
    {
        $sarpras_keluar = SarprasKeluar::where('id', $id)->first();
        $sarpras = Sarpras::where('id', $sarpras_keluar->sarpras_id)->first();
        $jumlah = $sarpras->jumlah + $sarpras_keluar->jumlah;

        Sarpras::where('id', $sarpras->id)
            ->update([
                'jumlah' => $jumlah
            ]);

        SarprasKeluar::destroy($id);

        SarprasDetail::where('sarpras_keluar_id', $sarpras_keluar->id)->delete();

        return redirect('/sarpras_keluar');
    }
}

resources/views/back/sarpras_keluar/create.blade.php
@extends('back.layouts.index')
@push('title', 'Create | Sarpras Keluar')
@section('content')
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Create Sarpras Keluar</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="#!">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Pages</span></li>
                <li><span>Sarpras</span></li>
                <li><span>Keluar</span></li>
                <li><span style="margin-right: 20px;">Create</span></li>
            </ol>
        </div>
    </header>
    <!-- Start page -->
    <div class="row">
        <div class="col-xs-6">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>
                    <h2 class="panel-title">Select Replacement</h2>
                </header>
                <div class="panel-body">
                    <form class="form-horizontal form-bordered" action="{{ route('sarpras_keluar.store') }}" method="POST" id="formcreate">
                        @csrf
                        <div class="form-group @error('sarpras') has-error @enderror">
                            <label class="col-md-3 control-label">Sarpras<span class="required">*</span></label>
                            <div class="col-md-8">
                                <select data-plugin-selectTwo class="form-control" name="sarpras" id="sarpras">
                                    <option selected disabled></option>
                                    <optgroup label="Barang">
                                        @foreach($sarpras_brg as $data)
                                        <option value="{{$data->id}}" data-stok="{{$data->jumlah}}" {{ old('sarpras') == $data->id ? 'selected' : null }}>{{$data->nama}}</option>
                                        @endforeach
                                    </optgroup>
                                    <optgroup label="Ruangan">
                                        @foreach($sarpras_rgn as $data)
                                        <option value="{{$data->id}}" data-stok="{{$data->jumlah}}" {{ old('sarpras') == $data->id ? 'selected' : null }}>{{$data->nama}}</option>
                                        @endforeach
                                    </optgroup>
                                </select>
                                @error('sarpras')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group" id="details">
                            <label class="col-md-3 control-label" for="total_stok">Stok</label>
                            <div class="col-md-8">
                                <h5 id="stok"></h5>
                            </div>
                        </div>
                        <div class="form-group @error('jumlah') has-error @enderror">
                            <label class="col-md-3 control-label" for="jumlah">Jumlah Keluar<span class="required">*</span></label>
                            <div class="col-md-8">
                                <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                                <input type="number" class="form-control" value="{{old('jumlah')}}" id="jumlah" name="jumlah">
                                @error('jumlah')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group" id="detailss">
                            <label class="col-md-3 control-label" for="total_stok">Total Stok</label>
                            <div class="col-md-8">
                                <h5 id="total_stok"></h5>
                            </div>
                        </div>
                        <div class="form-group @error('tanggal') has-error @enderror">
                            <label class="col-md-3 control-label" for="tanggal">Tanggal Masuk<span class="required">*</span></label>
                            <div class="col-md-8">
                                <input type="date" class="form-control" value="{{old('tanggal')}}" id="tanggal" name="tanggal">
                                @error('tanggal')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group @error('keterangan') has-error @enderror">
                            <label class="col-md-3 control-label" for="keterangan">Keterangan<span class="required">*</span></label>
                            <div class="col-md-8">
                                <textarea name="keterangan" id="keterangan" rows="5" class="form-control" placeholder="Describe keterangan">{{old('keterangan')}}</textarea>
                                @error('keterangan')
                                <span class="has-error" role="alert">
                                    <strong class="text-danger">{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-md-9 col-md-offset-3">
                            <button onclick="document.getElementById('formcreate').submit()" class="btn btn-primary">Submit</button>
                            <button onclick="document.getElementById('formcreate').reset()" class="btn btn-default">Reset</button>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <!-- End page -->
</section>
</div>
@endsection

@push('style')
<!-- Specific Page Vendor CSS -->
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/select2/select2.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap-timepicker/css/bootstrap-timepicker.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/dropzone/css/basic.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/dropzone/css/dropzone.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap-markdown/css/bootstrap-markdown.min.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/summernote/summernote.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/summernote/summernote-bs3.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/codemirror/lib/codemirror.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/codemirror/theme/monokai.css" />
@endpush

@push('script')
<script src="{{ asset('/back') }}/vendor/jquery-validation/jquery.validate.js"></script>
<!-- Specific Page Vendor -->
<script src="{{ asset('/back') }}/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js"></script>
<script src="{{ asset('/back') }}/vendor/select2/select2.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-multiselect/bootstrap-multiselect.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-maskedinput/jquery.maskedinput.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
<script src="{{ asset('/back') }}/vendor/fuelux/js/spinner.js"></script>
<script src="{{ asset('/back') }}/vendor/dropzone/dropzone.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-markdown/js/markdown.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-markdown/js/to-markdown.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-markdown/js/bootstrap-markdown.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/lib/codemirror.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/addon/selection/active-line.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/addon/edit/matchbrackets.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/mode/javascript/javascript.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/mode/xml/xml.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/mode/htmlmixed/htmlmixed.js"></script>
<script src="{{ asset('/back') }}/vendor/codemirror/mode/css/css.js"></script>
<script src="{{ asset('/back') }}/vendor/summernote/summernote.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-maxlength/bootstrap-maxlength.js"></script>
<script src="{{ asset('/back') }}/vendor/ios7-switch/ios7-switch.js"></script>
<script type="text/javascript">
    $('#details').hide();
    $('#detailss').hide();

    $(document).ready(function() {
        $("#sarpras").change(function() {
            var stok = $(this).find(':selected').data("stok");

            $('#details').show();
            $('#detailss').hide();
            $('#stok').text(stok);
            $('#jumlah').val('');
            $('#total_stok').text();
        })
    });
    $('#jumlah').keyup(function() {
        var a = parseInt($('#stok').text());
        var b = parseInt($('#jumlah').val());
        var c = a - b;
        $('#detailss').show();
        $('#total_stok').text(c);
    });
    $('#jumlah').click(function() {
        var a = parseInt($('#stok').val());
        var b = parseInt($('#jumlah').val());
        var c = a - b;
        $('#detailss').show();
        $('#total_stok').text(c);
    });
</script>
@endpush

@push('last_script')
<!-- Examples -->
<script src="{{ asset('/back') }}/javascripts/forms/examples.advanced.form.js"></script>
@endpush

resources/views/back/sarpras_keluar/index.blade.php
@extends('back.layouts.index')
@push('title', 'Keluar | Sarpras')
@section('content')
<section role="main" class="content-body">
    <header class="page-header">
        <h2>Sarpras Keluar</h2>

        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="#!">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Pages</span></li>
                <li><span>Sarpras</span></li>
                <li><span style="margin-right: 20px;">Keluar</span></li>
            </ol>

        </div>
    </header>
    <!-- Start page -->
    <section class="panel">
        <header class="panel-heading">
            <div class="panel-actions">
                <a href="#" class="fa fa-caret-down"></a>
                <a href="#" class="fa fa-times"></a>
            </div>

            <h2 class="panel-title">Daftar Sarpras Keluar</h2>
        </header>
        <div class="panel-body">
            <a href="{{ route('sarpras_keluar.create') }}" class="btn btn-primary rounded" style="margin-bottom: 10px;"><i class="fa fa-plus"></i> Create</a>
            <div id="content">
                @include('back.sarpras_keluar.table')
            </div>
        </div>
    </section>
    <!-- End page -->
</section>
</div>
@endsection

@push('style')
<!-- Specific Page Vendor CSS -->
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/select2/select2.css" />
<link rel="stylesheet" href="{{ asset('/back') }}/vendor/jquery-datatables-bs3/assets/css/datatables.css" />
@endpush

@push('modals')
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" style="color: black;" id="exampleModalLabel"> </h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <img id="img" src="" style="width: 29rem;" alt="">
                    </div>
                    <div class="col-md-5">
                        <div class="form-group">
                            <label for="tanggal">Tanggal</label>
                            <input type="date" class="form-control tanggal" id="tanggal">
                            <input type="hidden" class="id" id="id">
                            <input type="hidden" class="sarpras_id" id="sarpras_id">
                        </div>
                        <div class="form-group">
                            <label for="jumlah">Jumlah</label>
                            <input type="number" class="form-control jumlah" id="jumlah">
                            <input type="hidden" class="jumlah" id="old_jumlah">
                        </div>
                        <div class="form-group">
                            <label for="keterangan">Keterangan</label>
                            <input type="text" class="form-control keterangan" id="keterangan">
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal" id="update">Confirm</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
@endpush

@push('script')
<!-- Specific Page Vendor -->
<script src="{{ asset('/back') }}/vendor/select2/select2.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-datatables/media/js/jquery.dataTables.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-datatables/extras/TableTools/js/dataTables.tableTools.min.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-datatables-bs3/assets/js/datatables.js"></script>

<script>
    $(document).ready(function() {
        $(document).on('click', '#update', function() {
            const id = $('#id').val();
            const sarpras_id = $('#sarpras_id').val();
            const tanggal = $('#tanggal').val();
            const jumlah = $('#jumlah').val();
            const old_jumlah = $('#old_jumlah').val();
            const keterangan = $('#keterangan').val();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: 'sarpras_keluar/' + id,
                type: 'PUT',
                data: {
                    sarpras_id: sarpras_id,
                    tanggal: tanggal,
                    jumlah: jumlah,
                    old_jumlah: old_jumlah,
                    keterangan: keterangan,
                },
                success: function(data) {
                    $('#content').html(data);
                }
            })
        });
        $(document).on('click', '#edit', function() {
            var nama_sarpras = $(this).data('nama');
            var img_sarpras = $(this).data('img');
            var keterangan_draf = $(this).data('keterangan');
            var id = $(this).data('id');
            var sarpras_id = $(this).data('sarpras_id');
            var jumlah = $(this).data('jumlah');
            var tanggal = $(this).data('tanggal');

            $('.modal-title').text("Edit " + nama_sarpras);
            $('#img').attr('src', '/storage/' + img_sarpras);
            $('.keterangan').val(keterangan_draf);
            $('.id').val(id);
            $('.sarpras_id').val(sarpras_id);
            $('.jumlah').val(jumlah);
            $('.tanggal').val(tanggal);
        });
    });
</script>
@endpush

@push('last_script')
<!-- Examples -->
<script src="{{ asset('/back') }}/javascripts/tables/examples.datatables.default.js"></script>
@endpush

resources/views/back/sarpras_keluar/table.blade.php
<table class="table table-bordered table-striped mb-none" id="datatable-default">
    <thead>
        <tr>
            <th>#</th>
            <th>Nama</th>
            <th>Tanggal</th>
            <th class="hidden-phone">Jumlah</th>
            <th class="center">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($sarpras_keluar as $data)
        <tr>
            <th>{{$loop->iteration}}</th>
            <td>{{$data->sarpras->nama}}</td>
            <td>{{date('d F Y', strtotime($data->tanggal_keluar))}}</td>
            <td class="center">{{$data->jumlah}}</td>
            <th width="120px">
                <a href="{{ route('sarpras_keluar.show', $data->id) }}" class="mr-xs btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Detail"><i class="fa fa-eye"></i></a>
                <a id="edit" data-id="{{$data->id}}" data-tanggal="{{$data->tanggal_keluar}}" data-jumlah="{{$data->jumlah}}" data-keterangan="{{$data->keterangan}}" data-sarpras_id="{{ $data->sarpras_id }}" data-nama="{{ $data->sarpras->nama }}" data-img="{{ $data->sarpras->photo }}" data-toggle="modal" data-target="#exampleModal" class="mr-xs btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="Ubah"><i class="fa fa-pencil-square-o"></i></a>
                <form onclick="return confirm('Yakin ingin hapus ini?')" action="{{ route('sarpras_keluar.destroy', $data->id) }}" method="post" style="display: inline;">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Hapus">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </form>
            </th>
        </tr>
        @endforeach
    </tbody>
</table>