routes/web.php
<?php

use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\DashController;
use App\Http\Controllers\DraftController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RatingController;
use App\Http\Controllers\SarprasController;
use App\Http\Controllers\SarprasKeluarController;
use App\Http\Controllers\SarprasMasukController;
use App\Http\Controllers\ValidasiController;
use App\Http\Controllers\WhatsAppController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');

Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');

Route::get('/pengguna/export', [PenggunaController::class, 'userexport'])->name('pengguna.export');
Route::post('/pengguna/import', [PenggunaController::class, 'userimport'])->name('pengguna.import');
Route::resource('pengguna', PenggunaController::class);
Route::post('/pengguna/{id}/edit', [PenggunaController::class, 'password']);

Route::get('/', [DashController::class, 'welcome']);
Route::get('/dashboard', [DashController::class, 'index'])->name('dashboard');
Route::get('/barang', [DashController::class, 'barang']);
Route::get('/ruangan', [DashController::class, 'ruangan']);
Route::get('/sarpras_detail/{id}', [DashController::class, 'sarpras_detail']);
Route::get('/about', [DashController::class, 'about']);
Route::get('/contact', [DashController::class, 'contact']);
Route::get('/faqs', [DashController::class, 'faqs']);

Route::get('/draft_count', [DraftController::class, 'draft_count']);
Route::get('/draft_count/{id}', [DraftController::class, 'draft_count_update']);
Route::get('/draft/mini', [DraftController::class, 'mini_draft']);
Route::post('/draft/mini/destroy/{id}', [DraftController::class, 'mini_draft_destroy']);
Route::get('/draft_', [DraftController::class, 'draft_']);
Route::get('/draft_update/{id}', [DraftController::class, 'draft_update']);
Route::put('/draft_qty/{id}', [DraftController::class, 'update_qty']);
Route::resource('draft', DraftController::class);
Route::post('/draft_update/{id}', [DraftController::class, 'draft_update_delete']);
Route::post('/draft/print', [DraftController::class, 'print']);
Route::post('/cek_qrcode', [DraftController::class, 'cek_qr_code']);

Route::resource('sarpras', SarprasController::class);

Route::resource('sarpras_masuk', SarprasMasukController::class);

Route::resource('sarpras_keluar', SarprasKeluarController::class);

Route::resource('validasi', ValidasiController::class);
Route::put('/validasi_update/{id}', [ValidasiController::class, 'update_lanjut']);
Route::get('/validasi_edit/{id}', [ValidasiController::class, 'add_sarpras'])->name('validasi_edit.add');
Route::post('/validasi_edit', [ValidasiController::class, 'store_add_sarpras'])->name('validasi_edit.store');
Route::put('/validasi_edit/{id}', [ValidasiController::class, 'update_peminjaman'])->name('validasi_edit.update');
Route::delete('/validasi_edit/{id}', [ValidasiController::class, 'destroy_sarpras'])->name('validasi_edit.destroy');

Route::resource('peminjaman', PeminjamanController::class);

Route::resource('pengembalian', PengembalianController::class);

Route::get('belum_validasi', [ValidasiController::class, 'belum_validasi']);
Route::get('sudah_validasi', [ValidasiController::class, 'sudah_validasi']);

Route::resource('rating', RatingController::class);

Route::get('/ketersediaan', [LaporanController::class, 'ketersediaan']);
Route::get('/kerusakan', [LaporanController::class, 'kerusakan']);

Route::get('/profile', [ProfileController::class, 'index']);
Route::get('/edit', [ProfileController::class, 'index']);
Route::get('/changePassword', [ProfileController::class, 'index']);
Route::post('/edit/{id}', [ProfileController::class, 'update'])->name('update_profile');
Route::post('/changePassword', [ProfileController::class, 'password'])->name('changePassword');

// Route::match(['get', 'post'], '/botman', [BotManController::class, 'handle']);

Route::get('/perangkat', [WhatsAppController::class, 'perangkat']);
Route::put('/perangkat', [WhatsAppController::class, 'update_sender']);
Route::put('/perangkats', [WhatsAppController::class, 'restart']);

Route::get('/schedule', [WhatsAppController::class, 'schedule']);


/*
|--------------------------------------------------------------------------
| Note
|--------------------------------------------------------------------------
| - Disni saya menggunakan layanan WhatsApp Gateway dari wablas
|
|
*/

resources/views/back/layouts/footer.blade.php
</section>

@stack('modals')
<!-- Vendor -->
<script src="{{ asset('/back') }}/vendor/jquery/jquery.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap/js/bootstrap.js"></script>
<script src="{{ asset('/back') }}/vendor/nanoscroller/nanoscroller.js"></script>
<script src="{{ asset('/back') }}/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="{{ asset('/back') }}/vendor/magnific-popup/magnific-popup.js"></script>
<script src="{{ asset('/back') }}/vendor/jquery-placeholder/jquery.placeholder.js"></script>

@stack('script')

@if(Auth::user()->roles == 'BMN')
<div class="modal fade" id="modalBootstrapScanDraf" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Scan Draft</h4>
            </div>
            <div class="modal-body">
                <div id="reader" width="400px"></div>
            </div>
        </div>
    </div>
</div>

<script src="{{ asset('/back') }}/vendor/sweetalert/sweetalert2.all.min.js"></script>
<script src="{{ asset('/back') }}/vendor/qr-code/html5-qrcode.min.js"></script>
<script>
    document.getElementById("ScanQRDraft").onclick = function() {
        ScanDraft()
    };
    $(document).on('hidden.bs.modal', function() {
        html5QrcodeScanner.clear();
    });


    function onScanSuccess(decodedText, decodedResult) {
        // handle the scanned code as you like, for example:
        // console.log(`Code matched = ${decodedText}`, decodedResult);
        // $('#result').val(decodedText);

        let id = decodedText

        csrf_token = $('meta[name="csrf-token"]').attr('content');

        let timerInterval
        swal.fire({
            icon: 'info',
            title: 'Berhasil Scan',
            html: 'Mencari data dalam <b></b> detik.',
            timer: 2000,
            timerProgressBar: true,
            didOpen: () => {
                Swal.showLoading()
                const b = Swal.getHtmlContainer().querySelector('b')
                timerInterval = setInterval(() => {
                    b.textContent = Swal.getTimerLeft()
                }, 100)
            },
        }).then((result) => {
            if (result.dismiss) {
                $.ajax({
                    url: "/cek_qrcode",
                    type: 'POST',
                    data: {
                        '_method': 'POST',
                        '_token': csrf_token,
                        'qr_code': id
                    },
                    success: function(response) {
                        if (response.status_error) {
                            swal.fire({
                                icon: 'error',
                                title: 'Oops...',
                                text: 'Data tidak ditemukan!'
                            })
                        } else if (response.validasi) {
                            swal.fire({
                                icon: 'success',
                                title: 'Success!',
                                text: 'Data ditemukan !'
                            }).then((result) => {
                                window.location.href = 'http://127.0.0.1:8000/validasi/' + response.validasi
                            });
                        } else if (response.peminjaman) {
                            swal.fire({
                                icon: 'success',
                                title: 'Success!',
                                text: 'Data ditemukan !'
                            }).then((result) => {
                                window.location.href = 'http://127.0.0.1:8000/peminjaman/' + response.peminjaman
                            });
                        } else if (response.pengembalian) {
                            swal.fire({
                                icon: 'success',
                                title: 'Success!',
                                text: 'Data ditemukan !'
                            }).then((result) => {
                                window.location.href = 'http://127.0.0.1:8000/pengembalian/' + response.pengembalian
                            });
                        }
                    },
                    error: function(xhr) {
                        swal.fire({
                            type: 'error',
                            title: 'Oops..!',
                            text: 'Someting went wrong!'
                        });
                    }
                })
            }
        })
    }

    let html5QrcodeScanner = new Html5QrcodeScanner(
        "reader", {
            fps: 10,
            qrbox: {
                width: 320,
                height: 320
            }
        },
        /* verbose= */
        false);

    function ScanDraft() {
        html5QrcodeScanner.render(onScanSuccess);
    }
</script>
@endif

<!-- Theme Base, Components and Settings -->
<script src="{{ asset('/back') }}/javascripts/theme.js"></script>

<!-- Theme Custom -->
<script src="{{ asset('/back') }}/javascripts/theme.custom.js"></script>

<!-- Theme Initialization Files -->
<script src="{{ asset('/back') }}/javascripts/theme.init.js"></script>

@stack('last_script')

</body>

</html>

resources/views/back/layouts/header.blade.php
<!doctype html>
<html class="fixed">

<head>

    <!-- Basic -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta charset="UTF-8">
    <title>@stack('title')</title>
    <meta name="keywords" content="HTML5 Admin Template" />
    <meta name="description" content="JSOFT Admin - Responsive HTML5 Template">
    <meta name="author" content="JSOFT.net">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="{{ asset('/back') }}/vendor/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="{{ asset('/back') }}/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="{{ asset('/back') }}/vendor/bootstrap-datepicker/css/datepicker3.css" />

    <!-- Spesifik vendor  -->
    @if(Auth::user()->roles == 'BMN')
    <link rel="stylesheet" href="{{ asset('/back') }}/vendor/sweetalert/animate.min.css" />
    <link rel="stylesheet" href="{{ asset('/back') }}/vendor/sweetalert/sweetalert2.min.css" />
    @endif

    @stack('style')
    <!-- Theme CSS -->
    <link rel="stylesheet" href="{{ asset('/back') }}/stylesheets/theme.css" />

    <!-- Skin CSS -->
    <link rel="stylesheet" href="{{ asset('/back') }}/stylesheets/skins/default.css" />

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="{{ asset('/back') }}/stylesheets/theme-custom.css">

    <!-- Head Libs -->
    <script src="{{ asset('/back') }}/vendor/modernizr/modernizr.js"></script>

</head>

resources/views/back/layouts/index.blade.php
@include('back.layouts.header')
@include('back.layouts.navbar')
@include('back.layouts.sidebar')
@yield('content')
@include('back.layouts.footer')

resources/views/back/layouts/sidebar.blade.php
<div class="inner-wrapper">
    <!-- start: sidebar -->
    <aside id="sidebar-left" class="sidebar-left">

        <div class="sidebar-header">
            <div class="sidebar-title" style="color: white;">
                Navigation
            </div>
            <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
                <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
            </div>
        </div>

        <div class="nano">
            <div class="nano-content">
                <nav id="menu" class="nav-main" role="navigation">
                    <ul class="nav nav-main">
                        <li class="{{ request()->is('dashboard') ? 'nav-active' : '' }}">
                            <a href="/dashboard">
                                <i class="fa fa-home" aria-hidden="true"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        @if(Auth::user()->roles == 'BMN')
                        <li class="{{ request()->is('pengguna*') ? 'nav-active' : '' }}">
                            <a href="{{ route('pengguna.index') }}">
                                <span class="pull-right label label-primary">{{ count(App\Models\User::all()) }}</span>
                                <i class="fa fa-users" aria-hidden="true"></i>
                                <span>Pengguna</span>
                            </a>
                        </li>
                        @if(request()->is('sarpras*') )
                        <li class="nav-parent nav-expanded nav-active">
                            @else
                        <li class="nav-parent">
                            @endif
                            <a>
                                <i class="fa fa-copy" aria-hidden="true"></i>
                                <span>Sarpras</span>
                            </a>
                            <ul class="nav nav-children">
                                @if(request()->is('sarpras'))
                                <li class="{{ request()->is('sarpras') ? 'nav-active' : '' }}">
                                    @elseif(request()->is('sarpras/*'))
                                <li class="{{ request()->is('sarpras/*') ? 'nav-active' : '' }}">
                                    @else
                                <li>
                                    @endif
                                    <a href="{{ route('sarpras.index') }}">
                                        Master Data
                                    </a>
                                </li>
                                @if(request()->is('sarpras_masuk'))
                                <li class="{{ request()->is('sarpras_masuk') ? 'nav-active' : '' }}">
                                    @elseif(request()->is('sarpras_masuk/*'))
                                <li class="{{ request()->is('sarpras_masuk/*') ? 'nav-active' : '' }}">
                                    @else
                                <li>
                                    @endif
                                    <a href="{{ route('sarpras_masuk.index') }}">
                                        Sarpras Masuk
                                    </a>
                                </li>
                                @if(request()->is('sarpras_keluar'))
                                <li class="{{ request()->is('sarpras_keluar') ? 'nav-active' : '' }}">
                                    @elseif(request()->is('sarpras_keluar/*'))
                                <li class="{{ request()->is('sarpras_keluar/*') ? 'nav-active' : '' }}">
                                    @else
                                <li>
                                    @endif
                                    <a href="{{ route('sarpras_keluar.index') }}">
                                        Sarpras Keluar
                                    </a>
                                </li>
                            </ul>
                        </li>
                        @if(request()->is('*validasi') )
                        <li class="nav-parent nav-expanded nav-active">
                            @elseif(request()->is('validasi*'))
                        <li class="nav-parent nav-expanded nav-active">
                            @else
                        <li class="nav-parent">
                            @endif
                            <a>
                                <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                <span>Validasi</span>
                            </a>
                            <ul class="nav nav-children">
                                <li class="{{ request()->is('belum_validasi') ? 'nav-active' : '' }}">
                                    <a href="/belum_validasi">
                                        Belum Validasi
                                    </a>
                                </li>
                                <li class="{{ request()->is('sudah_validasi') ? 'nav-active' : '' }}">
                                    <a href="/sudah_validasi">
                                        Sudah Validasi
                                    </a>
                                </li>
                                @if(request()->is('validasi'))
                                <li class="{{ request()->is('validasi') ? 'nav-active' : '' }}">
                                    @elseif(request()->is('validasi*'))
                                <li class="{{ request()->is('validasi*') ? 'nav-active' : '' }}">
                                    @else
                                <li>
                                    @endif
                                    <a href="/validasi">
                                        Semua Validasi
                                    </a>
                                </li>
                            </ul>
                        </li>
                        @endif

                        @if(Auth::user()->roles == 'KTU' || Auth::user()->roles == 'Koordinator' )
                        @if(request()->is('*validasi') )
                        <li class="nav-parent nav-expanded nav-active">
                            @elseif(request()->is('validasi*'))
                        <li class="nav-parent nav-expanded nav-active">
                            @else
                        <li class="nav-parent">
                            @endif
                            <a>
                                <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                <span>Validasi</span>
                            </a>
                            <ul class="nav nav-children">
                                <li class="{{ request()->is('belum_validasi') ? 'nav-active' : '' }}">
                                    <a href="/belum_validasi">
                                        Belum Validasi
                                    </a>
                                </li>
                                <li class="{{ request()->is('sudah_validasi') ? 'nav-active' : '' }}">
                                    <a href="/sudah_validasi">
                                        Sudah Validasi
                                    </a>
                                </li>
                            </ul>
                        </li>
                        @endif
                        @if(request()->is('ketersediaan') )
                        <li class="nav-parent nav-expanded nav-active">
                            @elseif(request()->is('kerusakan'))
                        <li class="nav-parent nav-expanded nav-active">
                            @else
                        <li class="nav-parent">
                            @endif
                            <a>
                                <i class="fa fa-list-alt" aria-hidden="true"></i>
                                <span>Laporan</span>
                            </a>
                            <ul class="nav nav-children">
                                <li class="{{ request()->is('ketersediaan') ? 'nav-active' : '' }}">
                                    <a href="/ketersediaan">
                                        Ketersediaan
                                    </a>
                                </li>
                                <li class="{{ request()->is('kerusakan') ? 'nav-active' : '' }}">
                                    <a href="/kerusakan">
                                        Kerusakan
                                    </a>
                                </li>
                            </ul>
                        </li>
                        @if(Auth::user()->roles == 'BMN')
                        <hr class="sparator" separator>
                        <div class="sidebar-widget widget-tasks">
                            <div class="widget-header">
                                <h6 style="color: white;">MASTER DATA</h6>
                                <div class="widget-toggle" style="color: white;">+</div>
                            </div>
                            <div class="widget-content">
                                <ul class="list-unstyled m-none">
                                    <li class="nav-active">
                                        <a href="{{ route('peminjaman.index') }}">Peminjaman</a>
                                    </li>
                                    <li>
                                        <a href="{{ route('pengembalian.index') }}">Pengembalian</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <hr class="sparator" separator>
                        @if(request()->is('perangkat') )
                        <li class="nav-parent nav-expanded nav-active">
                            @elseif(request()->is('schedule') )
                        <li class="nav-parent nav-expanded nav-active">
                            @else
                        <li class="nav-parent">
                            @endif
                            <a>
                                <i class="fa fa-send" aria-hidden="true"></i>
                                <span>WhatsApp</span>
                            </a>
                            <ul class="nav nav-children">
                                <li class="{{ request()->is('perangkat') ? 'nav-active' : '' }}">
                                    <a href="/perangkat">
                                        Perangkat
                                    </a>
                                </li>
                                <li class="{{ request()->is('schedule') ? 'nav-active' : '' }}">
                                    <a href="/schedule">
                                        Schedule
                                    </a>
                                </li>
                            </ul>
                        </li>
                        @endif
                    </ul>
                </nav>
            </div>

        </div>

    </aside>
    <!-- end: sidebar -->